use anyhow::Result;
use async_trait::async_trait;
use serde_json::json;

use super::{GenerationRequest, LlmProvider};

pub struct MockProvider {
    model: String,
}

impl MockProvider {
    pub fn new(model: String) -> Self {
        Self { model }
    }
}

#[async_trait]
impl LlmProvider for MockProvider {
    async fn generate(&self, request: GenerationRequest) -> Result<String> {
        if request.user_prompt.contains("EVOLVER_CANDIDATE_BUNDLE") {
            let goal = extract_goal(&request.user_prompt);
            let cargo_toml = extract_snapshot_file(&request.user_prompt, "Cargo.toml")
                .unwrap_or_else(mock_cargo_toml);
            let main_rs = extract_snapshot_file(&request.user_prompt, "src/main.rs")
                .unwrap_or_else(|| {
                    "fn main() {\n    println!(\"evolver mock candidate\");\n}\n".to_string()
                });

            let payload = json!({
                "summary": format!("Mock candidate generated by {}", self.model),
                "files": [
                    {
                        "path": "Cargo.toml",
                        "content": cargo_toml
                    },
                    {
                        "path": "src/main.rs",
                        "content": mock_main_rs(&main_rs, &goal)
                    }
                ]
            });
            return Ok(serde_json::to_string_pretty(&payload)?);
        }

        Ok(format!(
            "[mock:{}]\nSYSTEM:\n{}\n\nUSER:\n{}",
            self.model, request.system_prompt, request.user_prompt
        ))
    }
}

fn mock_cargo_toml() -> String {
    r#"[package]
name = "evolver"
version = "0.1.0"
edition = "2024"

[dependencies]
"#
    .to_string()
}

fn mock_main_rs(current_main: &str, goal: &str) -> String {
    format!(
        "// Mock candidate note: staged for goal: {goal}\n{current_main}",
        goal = goal
    )
}

fn extract_goal(prompt: &str) -> String {
    let start = match prompt.find("Goal:\n") {
        Some(index) => index + "Goal:\n".len(),
        None => return "unspecified goal".to_string(),
    };
    let tail = &prompt[start..];
    let end = tail.find("\n\nReturn only").unwrap_or(tail.len());
    tail[..end].trim().to_string()
}

fn extract_snapshot_file(prompt: &str, path: &str) -> Option<String> {
    let marker = format!("=== {path} ===\n");
    let start = prompt.find(&marker)? + marker.len();
    let tail = &prompt[start..];
    let end = tail.find("\n\n=== ").unwrap_or(tail.len());
    Some(tail[..end].trim_end().to_string() + "\n")
}

#[cfg(test)]
mod tests {
    use super::{extract_goal, extract_snapshot_file, mock_main_rs};

    #[test]
    fn extracts_goal_body() {
        let prompt = "Goal:\nAdd plugins\n\nReturn only a JSON object";
        assert_eq!(extract_goal(prompt), "Add plugins");
    }

    #[test]
    fn extracts_snapshot_file_contents() {
        let prompt =
            "=== Cargo.toml ===\nname = \"evolver\"\n\n=== src/main.rs ===\nfn main() {}\n";
        let cargo = extract_snapshot_file(prompt, "Cargo.toml").expect("cargo section");
        assert!(cargo.contains("name = \"evolver\""));
    }

    #[test]
    fn mock_main_preserves_existing_source() {
        let main_rs = mock_main_rs("fn main() {}\n", "Add banner");
        assert!(main_rs.contains("fn main() {}"));
        assert!(main_rs.contains("Add banner"));
    }
}
